name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 11.0.11

      - name: Compile
        run: gradle install

      - name: Run tests
        run: gradle clean test --stacktrace
