name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 11.0.11

      - name: Run tests
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: --parallel clean test --stacktrace
          gradle-dependencies-cache-key: |
            **/*.gradle.kts
            **/gradle.properties
          properties: |
            kotlin.parallel.tasks.in.project=true
          concurrent: true
